# Generated by Django 4.2 on 2023-05-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
