# Generated by Django 4.2 on 2023-05-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='volunteers_reqired',
            new_name='volunteers_required',
        ),
    ]
