# Generated by Django 4.2 on 2023-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app_user',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
