# Generated by Django 4.2 on 2023-05-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_app_user_is_assistant_app_user_is_coordinator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='app_user',
            managers=[
            ],
        ),
    ]
