# Generated by Django 4.2 on 2023-05-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_app_user_is_assistant_app_user_is_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='about_section',
            field=models.TextField(null=True),
        ),
    ]
