# Generated by Django 4.2 on 2023-05-05 21:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_app_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='app_user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
